// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDC8kxmbTWb33iTH6wgy0hAm7mbcMfGh-E',
    appId: '1:505844682559:android:888a9ca556154c572ccd8a',
    messagingSenderId: '505844682559',
    projectId: 'barz777',
    storageBucket: 'barz777.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDYCc0--xBEZrZdQfpt3Tk3mXQTt5RH2o',
    appId: '1:505844682559:ios:94c091ebb8298a0b2ccd8a',
    messagingSenderId: '505844682559',
    projectId: 'barz777',
    storageBucket: 'barz777.firebasestorage.app',
    androidClientId: '505844682559-7hq3os8bgvg7p6moqekvrrev5r2j2gk3.apps.googleusercontent.com',
    iosClientId: '505844682559-5qciiqhmad3v412i2jlmivok1lk5ls08.apps.googleusercontent.com',
    iosBundleId: 'com.dobar.app',
  );

}